# Generated by Django 3.0.3 on 2020-03-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('stars', models.IntegerField()),
                ('photo', models.FilePathField()),
                ('studio', models.CharField(max_length=255)),
                ('actors', models.ManyToManyField(to='cinema.Actor')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.Genre')),
                ('keywords', models.ManyToManyField(to='cinema.Keyword')),
            ],
        ),
    ]
