# Generated by Django 3.0.4 on 2020-04-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='cinema.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='cinema.Keyword'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
    ]
