# Generated by Django 3.0.4 on 2020-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20200406_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
