# Generated by Django 3.0.4 on 2020-06-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20200504_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cinema.Actor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cinema.Keyword'),
            preserve_default=False,
        ),
    ]
