# Generated by Django 3.0.4 on 2020-06-15 11:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20200504_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Room')),
            ],
            options={
                'unique_together': {('row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Room')),
                ('seats', models.ManyToManyField(through='cinema.AvailableSeat', to='cinema.Seat')),
            ],
        ),
        migrations.AddField(
            model_name='availableseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Seat'),
        ),
        migrations.AddField(
            model_name='availableseat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Show'),
        ),
    ]
