# Generated by Django 3.0.4 on 2020-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20200614_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='cinema.Actor'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='cinema.Keyword'),
        ),
    ]
