# Generated by Django 3.0.4 on 2020-06-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20200615_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.Keyword'),
        ),
    ]
