# Generated by Django 3.0.4 on 2020-06-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_auto_20200615_0648'),
        ('cinema', '0006_auto_20200615_1321'),
    ]

    operations = [
    ]
