# Generated by Django 3.0.4 on 2020-06-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20200620_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'number')},
        ),
    ]
