# Generated by Django 3.0.4 on 2020-06-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_auto_20200620_1317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
